import React, { useState } from 'react';
import { X, Download, Copy, Check, FileJson, FileText, Printer, Shield } from 'lucide-react';
import { VerificationReportResponse } from '../types';

interface ReportExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  report: VerificationReportResponse;
}

export const ReportExportModal: React.FC<ReportExportModalProps> = ({
  isOpen,
  onClose,
  report,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const generateMarkdown = (): string => {
    const { candidate, summary, claims, urls, strengths, risk_notes } = report;
    let md = `# Resume Verification Report — ${candidate.name || 'Candidate'}\n\n`;
    md += `**File:** \`${report.filename}\` | **Date:** ${new Date(report.created_at).toLocaleDateString()}\n\n`;
    md += `## Summary\n`;
    md += `- **Evidence Coverage:** ${summary.evidence_coverage_percentage}%\n`;
    md += `- **URLs Found:** ${summary.total_urls} (${summary.accessible_urls} Accessible, ${summary.restricted_urls} Restricted, ${summary.broken_urls} Broken)\n`;
    md += `- **Claims Analyzed:** ${summary.total_claims}\n`;
    md += `- **Supported:** ${summary.supported_claims} | **Partially Supported:** ${summary.partially_supported_claims} | **Unverified:** ${summary.unverified_claims} | **Broken:** ${summary.broken_claims}\n\n`;

    if (strengths.length > 0) {
      md += `### Corroborated Strengths\n`;
      strengths.forEach((s) => (md += `- ✅ ${s}\n`));
      md += `\n`;
    }

    if (risk_notes.length > 0) {
      md += `### Verification Notes\n`;
      risk_notes.forEach((r) => (md += `- ℹ️ ${r}\n`));
      md += `\n`;
    }

    md += `## Claims Verification Breakdown\n\n`;
    claims.forEach((c, idx) => {
      md += `### ${idx + 1}. [${c.status}] ${c.claim_text}\n`;
      md += `* **Section:** ${c.section}\n`;
      if (c.associated_url) md += `* **Source URL:** ${c.associated_url}\n`;
      md += `* **Finding:** ${c.explanation}\n`;
      if (c.evidence_snippets.length > 0) {
        md += `* **Evidence:**\n`;
        c.evidence_snippets.forEach((ev) => {
          md += `  - *${ev.source_type}*: ${ev.snippet}\n`;
        });
      }
      md += `\n`;
    });

    md += `\n*Report generated by ResumeVerify AI.*`;
    return md;
  };

  const handleCopyMarkdown = () => {
    const md = generateMarkdown();
    navigator.clipboard.writeText(md);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadJSON = () => {
    const dataStr = 'data:text/json;charset=utf-8,' + encodeURIComponent(JSON.stringify(report, null, 2));
    const downloadAnchor = document.createElement('a');
    downloadAnchor.setAttribute('href', dataStr);
    downloadAnchor.setAttribute('download', `VerificationReport_${report.candidate.name?.replace(/\s+/g, '_') || 'Candidate'}.json`);
    document.body.appendChild(downloadAnchor);
    downloadAnchor.click();
    downloadAnchor.remove();
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/80 backdrop-blur-md animate-in fade-in">
      <div className="glass-panel rounded-2xl w-full max-w-lg overflow-hidden shadow-2xl border border-slate-800">
        
        {/* Header */}
        <div className="p-5 border-b border-slate-800 flex items-center justify-between">
          <div className="flex items-center space-x-2">
            <div className="w-8 h-8 rounded-lg bg-teal-500/10 border border-teal-500/30 flex items-center justify-center text-teal-400">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white">Export Verification Report</h3>
              <p className="text-xs text-slate-400">JSON, Markdown, or Printable Summary</p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="w-8 h-8 rounded-lg bg-slate-850 hover:bg-slate-800 flex items-center justify-center text-slate-400 hover:text-white transition"
          >
            <X className="w-4 h-4" />
          </button>
        </div>

        {/* Body Options */}
        <div className="p-6 space-y-4">
          
          {/* Option 1: Download JSON */}
          <div
            onClick={handleDownloadJSON}
            className="p-4 rounded-xl bg-slate-850/80 border border-slate-800 hover:border-teal-500/40 cursor-pointer group transition flex items-center justify-between"
          >
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-lg bg-slate-900 flex items-center justify-center text-teal-400 group-hover:scale-105 transition">
                <FileJson className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-sm font-bold text-white group-hover:text-teal-300">
                  Full Verification JSON
                </h4>
                <p className="text-xs text-slate-400">
                  Complete structured snapshot with manifests, AST trees, and evidence
                </p>
              </div>
            </div>
            <Download className="w-4 h-4 text-slate-400 group-hover:text-teal-400" />
          </div>

          {/* Option 2: Copy Markdown */}
          <div
            onClick={handleCopyMarkdown}
            className="p-4 rounded-xl bg-slate-850/80 border border-slate-800 hover:border-teal-500/40 cursor-pointer group transition flex items-center justify-between"
          >
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-lg bg-slate-900 flex items-center justify-center text-teal-400 group-hover:scale-105 transition">
                <FileText className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-sm font-bold text-white group-hover:text-teal-300">
                  Copy Markdown Summary
                </h4>
                <p className="text-xs text-slate-400">
                  Formatted summary for HR ATS, Notion, Slack, or GitHub issues
                </p>
              </div>
            </div>
            {copied ? (
              <span className="text-xs text-emerald-400 flex items-center gap-1 font-semibold">
                <Check className="w-4 h-4" /> Copied
              </span>
            ) : (
              <Copy className="w-4 h-4 text-slate-400 group-hover:text-teal-400" />
            )}
          </div>

          {/* Option 3: Print / PDF */}
          <div
            onClick={handlePrint}
            className="p-4 rounded-xl bg-slate-850/80 border border-slate-800 hover:border-teal-500/40 cursor-pointer group transition flex items-center justify-between"
          >
            <div className="flex items-center space-x-3">
              <div className="w-10 h-10 rounded-lg bg-slate-900 flex items-center justify-center text-teal-400 group-hover:scale-105 transition">
                <Printer className="w-5 h-5" />
              </div>
              <div>
                <h4 className="text-sm font-bold text-white group-hover:text-teal-300">
                  Print / Save as PDF
                </h4>
                <p className="text-xs text-slate-400">
                  Open browser print dialogue to save styled PDF verification document
                </p>
              </div>
            </div>
            <Printer className="w-4 h-4 text-slate-400 group-hover:text-teal-400" />
          </div>

        </div>

      </div>
    </div>
  );
};
